### ISSUE TITLE
Mini-AP-v4 Case .stl

### ISSUE THREAD

**Issue by timoknapp** [nlimper/Mini-AP-v4#1]
Hi @nlimper ,

since my AP v4 case had been delivered broken, I want to reprint the case myself. But It seems, that you did not yet share the `.stl` files for the v4 case yet. I could only find the v3 files.

Would be cool, if you could push them to this repo as well!

Best,
Timo

**Comment by nlimper** [comment]
You have mail ;-)

**Comment by Flawl3ssSWE** [comment]
@nlimper would it be possible for me to please get access to the STLs for the case as well? I picked up some screens and a V4 AP second hand, but unfortunately, the AP came without a case.

Thanks in advance!"
