### ISSUE TITLE
Display stopped working after a couple of weeks

### ISSUE THREAD

**Issue by AMajland** [nlimper/Mini-AP-v4#2]
Bought the access points assembled about two month ago from https://www.tindie.com/products/electronics-by-nic/openepaperlink-mini-ap-v3-zigbee-wifi-gateway

But the display stopped working more than 3 weeks ago, but not had the time to look into it.

After boot there is only backlight on the screen and the LED below it turns green and then starts pulsating. After a while it changes to a solid blue.

I can still access the access on its assigned ip address point but have lost connection to the tags (last seen 628 houte ago)

I then proceded to reset a tag (and gave it a new battery just to be sure) and it got it updating again - so the issue seems to just be the display

I assume that plastic can just be carefully broken apart to verify the inner connections ?

**Comment by AMajland** [comment]
Was running 2.5 beta 3 and just tried to updated to 2.52
but flashing failed

Progress: 82%
Packet could not be written!
Flashing /bootloader.bin
Erasing flash failed
...
C6 flash end
Flashing failed. :-(

**Comment by AMajland** [comment]
Updated ok in second try, but still no display (as expected)

**Comment by nlimper** [comment]
I’m currently from home, but I will send you a message tonight.

**Comment by nlimper** [comment]
You have mail :-)
