### ISSUE TITLE
Wrong default IP address at wiki

### ISSUE THREAD

**Issue by mcm1957** [nlimper/Mini-AP-v4#3]
The IP address at "flashing the esp32 c6" (https://github.com/nlimper/Mini-AP-v4/wiki/Building-the-Mini-AP-v4#flashing-the-esp32-c6 seems to be wrong. Wiki lists http://192.168.1.4/setup  while the display shows http://192.168.4.1/setup. The 4.1 address is working, so I guess the wiki is wrong.

I did not see a possibility to provide a PR, so I would ask to check / correct the wiki here.

**Comment by nlimper** [comment]
Thanks for noticing! I made the correction.
