### ISSUE TITLE
[Suggestion] Protective cover for flasher pins

### ISSUE THREAD

**Issue by mcm1957** [nlimper/Mini-AP-v4#5]
The cove for the AP v4 looks excellent. I only have one suggestion: Please evaluate to create a protective cover for the flasher pins at the rear. While the APv4 will be working as accesspoint those pins should be covered to avoid mechanical destruction end even more any elektical contact when being placed at some non isolating environment.

If there are any standard silicon plugs for the sort of connector, please document their type / name / .... so that unexperianced users can order them.

Thnaks for evaluating.

**Comment by nlimper** [comment]
Thanks for the suggestion. There is no standard cover for the plug, but I will try to design one to be 3d-printed. I will keep this issue open, once I know more, I will add it here.

**Comment by nlimper** [comment]
done! I designed a small dummy plug to cover the connector.
https://github.com/nlimper/Mini-AP-v4/tree/main/3d%20files
