### ISSUE TITLE
AP stopped working after a couple of weeks

### ISSUE THREAD

**Issue by MikeTsenatek** [nlimper/Mini-AP-v4#6]
Hey,

have the issue, that the AP stopped working today and got hot (but not smelling after magic smoke).

If I reconnect to USB the lower both LEDs are flasing a couple times.

What can I measure to figure out what was happend?

**Comment by nlimper** [comment]
Did you buy it as a kit or assembled? 
You can try to reinstall using install.openepaperlink.de 
If you bought it assembled and there is a hardware failure, contact me on nic at xs4all.nl and mention your tindie order number.

**Comment by MikeTsenatek** [comment]
Bought it full assembled.

Will send you a mail, as it isn't recognized from neither windows nor linux.
