### ISSUE TITLE
Pcb

### ISSUE THREAD

**Issue by matzeeg3** [nlimper/Mini-AP-v4#7]
Hi everyone, where can I get the PCB? Thanks in advance

**Comment by RyanNicole1104** [comment]
> 大家好，我在哪里可以买到 PCB？提前谢谢

Hi, Supply in what field? Do you have Gerber file, if so you can can send me inbox. We can help to manufacturing. 
nicolezheng2000@gmail.com

**Comment by pLazyN** [comment]
I have the same question. Since Nic does not sell them on his Tindie shop for now, I would like to make one myself. I found the schematics but no gerber files of the PCB. Is it intentional, or am I missing something?

**Comment by nlimper** [comment]
The hardware is not open source, sorry. If you want, you can create your own pcb from the schematic, or use any of the other options for obtaining an access point as described on the OpenEpaperLink repo.
